version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portal_booking_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    networks:
      - portal_booking_network
    external_links:
      - mysql:db

  nginx:
    image: nginx:alpine
    container_name: portal_booking_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - portal_booking_network
    depends_on:
      - app

volumes:
  db_data:
    driver: local

networks:
  portal_booking_network:
    driver: bridge
